repository: openml/automlbenchmark
#theme: jekyll-theme-slate
remote_theme: fongandrew/hydeout
markdown: kramdown

title: AutoML Benchmark
#description: config description

#sidebar_home_link: true
version: 0.9

hydeout:
  repo: https://github.com/openml/automlbenchmark
  version: 0.9

defaults:
  -
    scope:
      path: README.md
    values:
      title: ''
  -
    scope:
      path: HOWTO.md
    values:
      title: ''
